spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.130:8848
    alicloud:
      access-key: alicloud-access-key
      secret-key: alicloud-secret-key
      oss:
        bucket: gulimall-learning
        endpoint: oss-cn-hangzhou.aliyuncs.com
      # 发送短信接口的配置
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appcode: #
    sentinel:
      transport:
        dashboard: localhost:8080

  application:
    name: gulimall-third-party

server:
  port: 30000


management:
  endpoints:
    web:
      exposure:
        include: '*'


biz:
  oss:
    # resources-url是带有bucket的
    resources-url: http://192.168.64.130:9000/mall4cloud
    type: 1
    endpoint: http://192.168.64.130:9000
    bucket: gulimall-learning
    access-key-id: admin
    access-key-secret: admin123456
